Book2Product:
    type: object
    inherits:
        - BaseProduct
    config:
        fields:
            attributes:
                type: Book2Attributes
                resolve: '@=value'
            fields:
                type: Book2ContentFields
                resolve: '@=value'
