Book4Product:
    type: object
    inherits:
        - BaseProduct
    config:
        fields:
            attributes:
                type: Book4Attributes
                resolve: '@=value'
            fields:
                type: Book4ContentFields
                resolve: '@=value'
