Laptop6Product:
    type: object
    inherits:
        - BaseProduct
    config:
        fields:
            attributes:
                type: Laptop6Attributes
                resolve: '@=value'
            fields:
                type: Laptop6ContentFields
                resolve: '@=value'
