Laptop0ProductConnection:
    type: relay-connection
    config:
        nodeType: Laptop0Product
        connectionFields:
            sliceSize:
                type: Int!
            orderBy:
                type: String
