Mouse7ProductConnection:
    type: relay-connection
    config:
        nodeType: Mouse7Product
        connectionFields:
            sliceSize:
                type: Int!
            orderBy:
                type: String
