Mouse6ProductConnection:
    type: relay-connection
    config:
        nodeType: Mouse6Product
        connectionFields:
            sliceSize:
                type: Int!
            orderBy:
                type: String
