Mouse2Product:
    type: object
    inherits:
        - BaseProduct
    config:
        fields:
            attributes:
                type: Mouse2Attributes
                resolve: '@=value'
            fields:
                type: Mouse2ContentFields
                resolve: '@=value'
