OrdersByStatusPageBlockViews:
    type: enum
    config:
        values:
            default:
                value: '@ibexadesign/order_management/dashboard/blocks/orders_status.html.twig'
                description: 'Default block layout'
