# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Collaboration\Cart\Mapper\CartProxyMapper: ~

    App\Collaboration\Cart\Mapper\CartProxyMapperInterface:
        alias: App\Collaboration\Cart\Mapper\CartProxyMapper

    App\Collaboration\Cart\Persistence\Gateway\DatabaseGateway:
        arguments:
            $connection: '@ibexa.persistence.connection'
        tags:
            -   name: ibexa.collaboration.persistence.session.gateway
                discriminator: !php/const \App\Collaboration\Cart\CartSessionType::IDENTIFIER

    App\Collaboration\Cart\Persistence\Mapper:
        tags:
            -   name: ibexa.collaboration.persistence.session.mapper
                discriminator: !php/const \App\Collaboration\Cart\CartSessionType::IDENTIFIER

    App\Collaboration\Cart\Mapper\CartSessionPersistenceMapper:
        tags:
            -   name: ibexa.collaboration.service.session.persistence.mapper
                type: !php/const \App\Collaboration\Cart\CartSessionType::IDENTIFIER

    App\Collaboration\Cart\Mapper\CartSessionDomainMapper:
        tags:
            -   name: ibexa.collaboration.service.session.domain.mapper
                type: App\Collaboration\Cart\Persistence\Values\CartSession

    App\Collaboration\Cart\PermissionResolverDecorator:
        decorates: Ibexa\Contracts\ProductCatalog\PermissionResolverInterface

    App\Collaboration\Cart\CartResolverDecorator:
        decorates: Ibexa\Contracts\Cart\CartResolverInterface
